name: Create Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read package.json
      id: package
      run: echo "::set-output name=version::$(jq -r '.version' package.json)"

    - name: Zip files
      run: |
        zip -r release-${{ steps.package.outputs.version }}.zip .

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        tag_name: ${{ steps.package.outputs.version }}
        release_name: Release ${{ steps.package.outputs.version }}
        body: |
          Initial release.
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-${{ steps.package.outputs.version }}.zip
        asset_name: release-${{ steps.package.outputs.version }}.zip
        asset_content_type: application/zip
